# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_text', models.CharField(max_length=200)),
                ('distance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calpetrol.Source'),
        ),
    ]
