# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calpetrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=200)),
                ('car_use', models.IntegerField(default=0)),
            ],
        ),
    ]
