# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calpetrol', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=200)),
                ('destination_text', models.CharField(max_length=200)),
                ('distance', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='source',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
